import React, { useState, useCallback, useRef, useEffect } from 'react'
import _ from 'lodash'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ColorPicker from '../components/ColorPicker/ColorPicker'
import ColorMood from '../components/ColorMood/ColorMood'

export default function Home() {
  const redInput = useRef(255);
  const greenInput = useRef(191);
  const blueInput = useRef(191);
  const [colorMood, setColorMood] = useState('');
  const [color, setColor] = useState("#000000");

  useEffect(() => {
    fetchColorInfo();
  }, [redInput.current.value, greenInput.current.value, blueInput.current.value]);

  const fetchColorInfo = useCallback(_.debounce(async () => {
    const fetchUrl = `http://localhost:3000/color-mood?color=rgb(${redInput.current.value},${greenInput.current.value},${blueInput.current.value})`;
    console.log(fetchUrl);
    const response = await fetch(fetchUrl);
    const data = await response.json();
    console.log(response);
    setColorMood(`${data.name}:\n ${data.mood}`);
    console.log(colorMood)
  }, 1000), []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        < ColorPicker
          color={color}
          setColor={setColor}
          redInput={redInput}
          greenInput={greenInput}
          blueInput={blueInput} />

        <ColorMood colorMood={colorMood} />
      </main>
    </div>
  )
}
