import React, { useState, useCallback, useRef, useEffect } from 'react'
import _ from 'lodash'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ColorPicker from '../components/ColorPicker/ColorPicker'
import ColorMood from '../components/ColorMood/ColorMood'

export default function Home() {
  const [red, setRed] = useState(0)
  const [green, setGreen] = useState(0)
  const [blue, setBlue] = useState(0)
  const [colorMood, setColorMood] = useState('');
  const [color, setColor] = useState("#000000");

  useEffect(() => {
    console.log(red, green, blue);
    fetchColorInfo();
  }, [red, green, blue]);

  const fetchColorInfo = useCallback(_.debounce(async () => {
    const fetchUrl = `http://localhost:3000/color-mood?color=rgb(${red},${green},${blue})`;
    console.log(fetchUrl);
    const response = await fetch(fetchUrl);
    const data = await response.json();
    setColorMood(data.mood);
    console.log(colorMood)
  }, 1000), [red, green, blue]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        < ColorPicker
          color={color}
          setColor={setColor}
          red={red}
          green={green}
          blue={blue}
          setRed={setRed}
          setGreen={setGreen}
          setBlue={setBlue} />

        < ColorMood mood={colorMood} />
      </main>
    </div>
  )
}
